version: '2'

services:

  buildservice.endpoint:
    image: csclassroom/buildservice.endpoint${TAG}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10001:80"
    volumes:
      - ./appsettings.Environment.json:/app/appsettings.Environment.json
      - /tmp/CSClassroom:/tmp/CSClassroom
      - /var/run/docker.sock:/var/run/docker.sock