FROM openjdk:8-jdk

# Installs Ant
ENV ANT_VERSION 1.9.4
RUN cd && \
    wget -q http://archive.apache.org/dist/ant/binaries/apache-ant-${ANT_VERSION}-bin.tar.gz && \
    tar -xzf apache-ant-${ANT_VERSION}-bin.tar.gz && \
    mv apache-ant-${ANT_VERSION} /opt/ant && \
    rm apache-ant-${ANT_VERSION}-bin.tar.gz
ENV ANT_HOME /opt/ant
ENV PATH ${PATH}:/opt/ant/bin

RUN mkdir -p /usr/local/share/java
RUN wget http://search.maven.org/remotecontent?filepath=junit/junit/4.12/junit-4.12.jar -O /usr/local/share/java/junit-4.12.jar
RUN wget http://search.maven.org/remotecontent?filepath=org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar -O /usr/local/share/java/hamcrest-core-1.3.jar

COPY target/JavaProjectRunner-0.0.1-SNAPSHOT-jar-with-dependencies.jar /usr/local/share/java/JavaProjectRunner.jar
COPY run.sh /ProjectRunner/run.sh
WORKDIR /ProjectRunner

ENTRYPOINT ["/bin/bash", "-c", "./run.sh"]